import { DocumentItem } from "./types";

const now = new Date();
const subtractDays = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_DOCUMENTS: DocumentItem[] = [
    {
        id: "d1",
        title: "Gecombineerde Opgave 2024 - Definitief",
        filename: "GO_2024_dossier_v2.pdf",
        category: "RVO_GLB",
        folder: "Aangiftes 2024",
        docType: "PDF",
        year: 2024,
        status: "ok",
        priority: "normal",
        source: "export",
        uploadedAt: subtractDays(2),
        updatedAt: subtractDays(2),
        tags: ["GO", "Aangifte", "RVO"],
        isPinned: true
    },
    {
        id: "d2",
        title: "Mesttransport Bonnen April",
        filename: "VDM_April_2024_scan.pdf",
        category: "MEST",
        folder: "Transporten",
        docType: "PDF",
        year: 2024,
        status: "needs_review",
        priority: "urgent",
        source: "manual",
        linkedEntities: [{ kind: "melding", id: "m12", label: "Melding 8829" }],
        uploadedAt: subtractDays(5),
        updatedAt: subtractDays(5),
        tags: ["Transport", "Mest", "VDM"],
        notes: "Controleren of handtekening chauffeur zichtbaar is."
    },
    {
        id: "d3",
        title: "Bodemanalyserapport Perceel 12",
        filename: "eurofins_p12_2023.pdf",
        category: "STIKSTOF",
        folder: "Bodemanalyses",
        docType: "PDF",
        year: 2023,
        status: "expired",
        priority: "soon",
        source: "manual",
        linkedEntities: [{ kind: "perceel", id: "p12", label: "Perceel 12 - Achterveld" }],
        uploadedAt: subtractDays(400),
        updatedAt: subtractDays(400),
        tags: ["Bodem", "Fosfaat", "Derogatie"],
        notes: "Nieuwe analyse nodig voor 2025."
    },
    {
        id: "d4",
        title: "Derogatie Beschikking 2024",
        filename: "derogatie_2024.pdf",
        category: "MEST",
        folder: "Vergunningen",
        docType: "PDF",
        year: 2024,
        status: "ok",
        priority: "normal",
        source: "regelradar",
        uploadedAt: subtractDays(60),
        updatedAt: subtractDays(60),
        tags: ["Derogatie", "Beschikking"],
        isPinned: true
    },
    {
        id: "d5",
        title: "Jaaropgave 2023 Concept",
        filename: "jaaropgave_2023_v1.xls",
        category: "ACCOUNTANT_BANK",
        folder: "Jaarcijfers",
        docType: "XLS",
        year: 2023,
        status: "missing_info",
        priority: "normal",
        source: "advisor",
        uploadedAt: subtractDays(10),
        updatedAt: subtractDays(10),
        tags: ["Boekhouding", "Belasting"],
        notes: "Wachten op definitieve melkdata."
    },
    {
        id: "d6",
        title: "NVWA Controle Rapport",
        filename: "nvwa_visit_feb_2024.pdf",
        category: "NVWA",
        folder: "Inspecties",
        docType: "PDF",
        year: 2024,
        status: "ok",
        priority: "normal",
        source: "manual",
        uploadedAt: subtractDays(90),
        updatedAt: subtractDays(90),
        tags: ["Controle", "NVWA"],
    },
    {
        id: "d7",
        title: "Pachtovereenkomst De Vries",
        filename: "pacht_devries_signed.pdf",
        category: "CONTRACTEN",
        folder: "Grondzaken",
        docType: "PDF",
        year: 2024,
        status: "ok",
        priority: "normal",
        source: "manual",
        uploadedAt: subtractDays(120),
        updatedAt: subtractDays(120),
        tags: ["Pacht", "Contract"],
    },
    {
        id: "d8",
        title: "Subsidieaanvraag Jonge Landbouwers",
        filename: "jola_aanvraag_2024.pdf",
        category: "SUBSIDIES",
        folder: "Investeringen",
        docType: "PDF",
        year: 2024,
        status: "needs_review",
        priority: "soon",
        source: "dossierbouwer",
        uploadedAt: subtractDays(15),
        updatedAt: subtractDays(1),
        tags: ["JOLA", "Subsidie"],
    },
    {
        id: "d9",
        title: "Foto Bufferstrook Slootkant",
        filename: "IMG_20240501.jpg",
        category: "RVO_GLB",
        folder: "Bewijslast",
        docType: "IMAGE",
        year: 2024,
        status: "ok",
        priority: "normal",
        source: "manual",
        uploadedAt: subtractDays(3),
        updatedAt: subtractDays(3),
        tags: ["Bufferstrook", "Foto"],
    },
];
